app:
  name: "Muhajir Foundation API"
  version: "1.0.0"
  debug: false
  api_v1_str: "/api/v1"

database:
  driver: "postgresql"
  host: "localhost"
  port: 5432
  name: "muhajir_foundation"
  user: "coder"
  password: "Halil4983301..!"
  pool_size: 5
  max_overflow: 10

security:
  secret_key: "71c9b85af2b1c45a11d84b1164596617c96af2cba08d2c0df769ed76b2fad72d"
  algorithm: "HS256"
  access_token_expire_minutes: 30

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "app.log"

cors:
  origins:
    - "http://localhost:3000"
    - "http://localhost:8000"
  methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
  headers:
    - "Content-Type"
    - "Authorization"

email:
  username: "your-email@gmail.com"
  password: "your-app-password"
  from: "your-email@gmail.com"
  port: 587
  server: "smtp.gmail.com"