app:
  name: "Muhajir Foundation API"
  version: "1.0.1"
  debug: false
  api_v1_str: "/api/v1"
  workers: 4
  timeout: 120

database:
  driver: "postgresql"
  host: "localhost"
  port: 5432
  name: "muhajirfoundation"
  user: "your_db_user"
  password: "your_db_password"
  pool_size: 5
  max_overflow: 10
  pool_timeout: 30
  pool_recycle: 1800
  echo: false

security:
  secret_key: "your_secret_key"
  algorithm: "HS256"
  access_token_expire_minutes: 30
  refresh_token_expire_days: 7
  rate_limit: 100
  rate_limit_period: 60

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "app.log"
  max_size: 10485760
  backup_count: 5

cors:
  origins:
    - "http://localhost:3000"
    - "http://localhost:8000"
  methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
  headers:
    - "Content-Type"
    - "Authorization"
  allow_credentials: true
  max_age: 3600

email:
  username: "your-email@gmail.com"
  password: "your-app-password"
  from: "your-email@gmail.com"
  port: 587
  server: "smtp.gmail.com"
  use_tls: true
  timeout: 30

cache:
  type: "redis"
  host: "localhost"
  port: 6379
  db: 0
  default_timeout: 300

metrics:
  enabled: true
  port: 9090
  path: "/metrics"

queue:
  type: "redis"
  host: "localhost"
  port: 6379
  db: 1
  max_retries: 3
  retry_delay: 60

cluster:
  enabled: false
  nodes: []
  sync_interval: 60

pinata_api_key: "your_pinata_api_key"
pinata_api_secret: "your_pinata_api_secret" 