"""update wallets and campaigns

Revision ID: 34567fb2ae5e
Revises: 494f6a641904
Create Date: 2025-04-25 12:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34567fb2ae5e'
down_revision: Union[str, None] = '494f6a641904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем внешний ключ campaign_id
    op.drop_constraint('wallets_campaign_id_fkey', 'wallets', type_='foreignkey')
    # Удаляем колонку campaign_id
    op.drop_column('wallets', 'campaign_id')
    
    # Добавляем колонку target_amount в donation_campaigns
    op.add_column('donation_campaigns', sa.Column('target_amount', sa.Numeric(10, 2), nullable=False))
    # Добавляем внешний ключ wallet_id
    op.add_column('donation_campaigns', sa.Column('wallet_id', sa.Integer(), nullable=False))
    op.create_foreign_key('donation_campaigns_wallet_id_fkey', 'donation_campaigns', 'wallets', ['wallet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем внешний ключ wallet_id
    op.drop_constraint('donation_campaigns_wallet_id_fkey', 'donation_campaigns', type_='foreignkey')
    # Удаляем колонку wallet_id
    op.drop_column('donation_campaigns', 'wallet_id')
    # Удаляем колонку target_amount
    op.drop_column('donation_campaigns', 'target_amount')
    
    # Добавляем колонку campaign_id обратно
    op.add_column('wallets', sa.Column('campaign_id', sa.Integer(), nullable=True))
    # Добавляем внешний ключ campaign_id
    op.create_foreign_key('wallets_campaign_id_fkey', 'wallets', 'donation_campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
