"""add target_amount to donation_campaigns

Revision ID: 7fa7c45b6eae
Revises: a6d6d2d23ebe
Create Date: 2025-04-22 17:47:24.791281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fa7c45b6eae'
down_revision: Union[str, None] = 'a6d6d2d23ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donation_campaigns', sa.Column('target_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donation_campaigns', 'target_amount')
    # ### end Alembic commands ###
